### ISSUE TITLE
Cache elements in variables

### ISSUE THREAD

**Issue by joostf** [SCNMC/connect-your-tribe-fdnd-visitekaartje#1]
https://github.com/SCNMC/connect-your-tribe-fdnd-visitekaartje/blob/16b463aad7d04f75c87d02dc578a5ce653d0063d/scripts/scripts.js#L16-L21

[See our best practices](https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md#cache-elements-in-variables)

**Comment by SCNMC** [comment]
fixed.
