### ISSUE TITLE
Use a separate render function, for better readability

### ISSUE THREAD

**Issue by joostf** [SCNMC/connect-your-tribe-fdnd-visitekaartje#3]
https://github.com/SCNMC/connect-your-tribe-fdnd-visitekaartje/blob/16b463aad7d04f75c87d02dc578a5ce653d0063d/scripts/scripts.js#L14-L26

[See our best practices](https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md#keep-functions-simple)

**Comment by SCNMC** [comment]
fixed.
